### ISSUE TITLE
Ingress cannot configure multiple paths of same backend 

### ISSUE THREAD

**Issue by addozhang** [flomesh-io/fsm#215]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                        [ ]
- Gateway API - GatewayClass     [ ]
- Gateway API - Gateway          [ ]
- Gateway API - HTTPRoute        [ ]
- Gateway API - TLSRoute         [ ]
- Gateway API - TCPRoute         [ ]
- Gateway API - UDPRoute         [ ]
- Gateway API - PolicyReference  [ ]
- Ingress                        [x]
- Egress                         [ ]
- MultiCluster                   [ ]
- PIPY Control Plane             [ ]
- PIPY Script/Config             [ ] 
- CLI Tool                       [ ]
- Metrics                        [ ]
- Certificate Management         [ ]
- Sidecar Injection              [ ]
- Logging                        [ ]
- Debugging                      [ ]
- Tests                          [ ]
- Demo                           [ ]
- CI System                      [ ]

**Expected behavior**:

It can route requests to different paths of same backend svc configured in Ingress.

**Steps to reproduce the bug (as precisely as possible)**:

1. Deploy httpbin deployment and service.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 14001
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "-b", "0.0.0.0:14001", "httpbin:app", "-k", "gevent"]
        ports:
        - containerPort: 14001
```
2. Apply Ingress 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  ingressClassName: pipy
  rules:
  - host: httpbin.org
    http:
      paths:
        - path: /headers
          pathType: Prefix
          backend:
            service:
              name: httpbin
              port:
                number: 14001
        - path: /get
          pathType: Prefix
          backend:
            service:
              name: httpbin
              port:
                number: 14001
```

3. try to access /headers and /get, but can not reach /get
4. check route config but path `/get` not there 
```json
{
   "trustedCAs": [],
   "certificates": {},
   "routes": {
      "/mesh/*": {
         "service": "fsm/fsm-repo-service:repo",
         "rewrite": [
            "^/mesh/?",
            "/"
         ]
      },
      "httpbin.org/headers/*": {
         "service": "httpbin/httpbin:http"
      }
   },
   "services": {
      "fsm/fsm-repo-service:repo": {
         "balancer": "round-robin",
         "upstream": {
            "endpoints": [
               {
                  "ip": "10.42.0.8",
                  "port": 6060
               }
            ]
         }
      },
      "httpbin/httpbin:http": {
         "balancer": "round-robin",
         "upstream": {
            "endpoints": [
               {
                  "ip": "10.42.0.9",
                  "port": 14001
               }
            ]
         }
      }
   }
}
```

**How was FSM installed?**:

helm

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- FSM version (use `fsm version`): 0.2.0
- Kubernetes version (use `kubectl version`): 1.23
- Size of cluster (number of worker nodes in the cluster): one node 
- Others:
