### ISSUE TITLE
feat: Support more deployment template spec in IngressDeployment

### ISSUE THREAD

**Issue by keveinliu** [flomesh-io/fsm#61]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality              [x]
- Install                        [ ] 
- Gateway API - GatewayClass     [ ] 
- Gateway API - Gateway          [ ] 
- Gateway API - HTTPRoute        [ ] 
- Gateway API - TLSRoute         [ ] 
- Gateway API - TCPRoute         [ ] 
- Gateway API - UDPRoute         [ ] 
- Gateway API - PolicyReference  [ ] 
- Ingress                        [x] 
- Egress                         [ ] 
- MultiCluster                   [ ] 
- PIPY Control Plane             [ ] 
- PIPY Script/Config             [ ] 
- CLI Tool                       [ ] 
- Metrics                        [ ] 
- Certificate Management         [ ] 
- Sidecar Injection              [ ] 
- Logging                        [ ] 
- Debugging                      [ ] 
- Tests                          [ ] 
- Demo                           [ ] 
- CI System                      [ ] 
- Project Release                [ ]

**Possible use cases**

FSM Version: v0.1.4
Currently it's not possible to set node selector labels and resources limits while deploying namespaced ingress controller. 
To support nodeSelector and resources limits helps in production environment. The deployment yaml file might be like this:
```
apiVersion: flomesh.io/v1alpha1
kind: IngressDeployment
metadata:
  name: ingress-deployment-102
  namespace: test-100
spec:
  serviceType: LoadBalancer
  ports:
  - name: http
    port: 102
    protocol: TCP
    nodePort: 30102
  nodeSelect:
    somelabel: key1
  resources:
    limits:
      cpu: "2"
      memory: 1G
    requests:
      cpu: 500m
      memory: 128M
  env:
  - name: a1
    value: abc
  - name: b1
    value: xyz
  - name: c1
    value: nnn
  serviceAnnotations:
    flomesh.io/test1: fsm1
    flomesh.io/test2: fsm2
    flomesh.io/test3: fsm3
```
